CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE financial_instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    CONSTRAINT chk_financial_instruments_type
        CHECK (type IN ('STOCK', 'ETF', 'BOND', 'CRYPTO', 'FOREX', 'INDEX', 'OTHER'))
);

CREATE TABLE portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT fk_portfolios_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    financial_instrument_id BIGINT NOT NULL,
    quantity NUMERIC(20, 8) NOT NULL,
    CONSTRAINT fk_holdings_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE,
    CONSTRAINT fk_holdings_financial_instrument
        FOREIGN KEY (financial_instrument_id) REFERENCES financial_instruments(id) ON DELETE RESTRICT,
    CONSTRAINT chk_holdings_quantity_non_negative
        CHECK (quantity >= 0),
    CONSTRAINT uq_holdings_portfolio_financial_instrument
        UNIQUE (portfolio_id, financial_instrument_id)
);

CREATE TABLE stock_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    financial_instrument_id BIGINT NOT NULL,
    price NUMERIC(19, 4) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_stock_prices_financial_instrument
        FOREIGN KEY (financial_instrument_id) REFERENCES financial_instruments(id) ON DELETE RESTRICT,
    CONSTRAINT chk_stock_prices_price_non_negative
        CHECK (price >= 0)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    financial_instrument_id BIGINT NOT NULL,
    threshold NUMERIC(19, 4) NOT NULL,
    condition VARCHAR(10) NOT NULL,
    CONSTRAINT fk_alerts_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_alerts_financial_instrument_symbol
        FOREIGN KEY (financial_instrument_id) REFERENCES financial_instruments(id) ON DELETE RESTRICT,
    CONSTRAINT chk_alerts_threshold_non_negative
        CHECK (threshold >= 0),
    CONSTRAINT chk_alerts_condition
        CHECK (condition IN ('ABOVE', 'BELOW'))
);

CREATE INDEX idx_financial_instruments_symbol ON financial_instruments(symbol);
CREATE INDEX idx_portfolios_user_id ON portfolios(user_id);
CREATE INDEX idx_holdings_portfolio_id ON holdings(portfolio_id);
CREATE INDEX idx_holdings_financial_instrument_id ON holdings(financial_instrument_id);
CREATE INDEX idx_stock_prices_financial_instrument_timestamp ON stock_prices(financial_instrument_id, timestamp);
CREATE INDEX idx_alerts_user_id ON alerts(user_id);
CREATE INDEX idx_alerts_symbol ON alerts(financial_instrument_id);
